# Generated by Django 3.0.4 on 2020-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
