# Generated by Django 3.0.4 on 2020-03-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorries', '0002_auto_20200325_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorry',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorries', to=settings.AUTH_USER_MODEL),
        ),
    ]
